### ISSUE TITLE
Add some examples and/or methods for helping make maps

### ISSUE THREAD

**Issue by sckott** [sckott/pygbif#14]

**Comment by sckott** [comment]
if anyone has examples with non-heavy dependencies for people to get started with, i'm all ears

**Comment by ninsbl** [comment]
In GRASS GIS, I used your excellent library for:
https://grass.osgeo.org/grass76/manuals/addons/v.in.pygbif.html

Data goes right into GIS for all sorts of map making and combination with other data.

One could also think if a simple QGIS plugin wrapped around pygbif....

Personally, I would keep pygbif focused on the interaction with GBIF, following the Linux principle, do one thing and do it well...

Anyway, thanks for pygbif!

**Comment by sckott** [comment]
Thanks for the note @ninsbl  Neat to see this use case for pygbif!

I agree to keep it simple. We do have a very minimal mapping api https://github.com/sckott/pygbif#maps-module that usess GBIF's maps web API, but I don't plan on building that out any further
