### ISSUE TITLE
Make sure pygbif is python 3 compatible

### ISSUE THREAD

**Issue by sckott** [sckott/pygbif#19]

**Comment by timlinux** [comment]
Thank you for making this library! Can you share what the status is for python 3 support?

**Comment by sckott** [comment]
thx for your question @timlinux 

i do test it on python 2.7 and three different versions of python 3 https://travis-ci.org/sckott/pygbif/builds/332893995 - so I think it's probably good to go for python 3, but it's possible i've missed some things. is there some sort of linter or so to make sure a python lib is python 3 compatible?

**Comment by sckott** [comment]
python 3 only now
