### ISSUE TITLE
Add occurrence facet support

### ISSUE THREAD

**Issue by peterdesmet** [sckott/pygbif#30]
See http://lists.gbif.org/pipermail/api-users/2016-June/000344.html. These facets allow to get quick counts for any occurrence search.

**Comment by sckott** [comment]
* `facet`
* `facetMincount`
* `facetMultiselect `
* support facet paging

**Comment by peterdesmet** [comment]
Cool! Gotta test this when I find some time.

**Comment by sckott** [comment]
cool, hopefully it works as expected for you
