### ISSUE TITLE
Should we support maps API?

### ISSUE THREAD

**Issue by sckott** [sckott/pygbif#41]
Should we support the maps API?

If so, def. wait for /v2 to come out

**Comment by peterdesmet** [comment]
I have no use case (yet).

**Comment by sckott** [comment]
Okay, me neither. Recently accepted a PR in the R client for maps, main use case getting raster objects which users can use in analysis pipelines, or viz

**Comment by sckott** [comment]
maps v2 is out https://www.gbif.org/developer/maps :tada:

**Comment by sckott** [comment]
@peterdesmet if you have any interest, you can test this out - installing from the `map-api` branch

**Comment by peterdesmet** [comment]
I'd like to, but don't have the time for it right now. 😬

**Comment by sckott** [comment]
if you want to try the maps module:

```sh
pip install https://github.com/sckott/pygbif/archive/map-api.zip
```

```python3
from pygbif import maps
out = maps.map(taxonKey = 2435098)
out.response
out.path
out.img
out.plot()

out = maps.map(taxonKey = 2480498, year = range(2007, 2011+1))
out.plot()
```
