### ISSUE TITLE
occurrence search returns observation outside specified polygon provided in geometry parameter

### ISSUE THREAD

**Issue by aubreymoore** [sckott/pygbif#46]
When I search for _Oryctes rhinoceros_ within a bounding box for Guam, I get an occurrence record for the Philippines. Using python 2.7/pygbif 0.2.0.

from pygbif import occurrences as occ
occ.search(scientificName='Oryctes rhinoceros',
          geometry='POLYGON((144.61 13.22, 144.61 13.66, 144.96 13.66, 144.96 13.22, 144.61 13.22))',
          limit=1)

Returns:

{u'count': 3,
 u'endOfRecords': False,
 u'facets': [],
 u'limit': 1,
 u'offset': 0,
 u'results': [{u'acceptedScientificName': u'Oryctes rhinoceros (Linnaeus, 1758)',
   u'acceptedTaxonKey': 4995642,
   u'basisOfRecord': u'HUMAN_OBSERVATION',
   u'catalogNumber': u'4864787',
   u'class': u'Insecta',
   u'classKey': 216,
   u'collectionCode': u'Observations',
   u'coordinateUncertaintyInMeters': 88056.0,
   u'country': u'Philippines',
   u'countryCode': u'PH',
   u'crawlId': 141,
   u'datasetKey': u'50c9509d-22c7-4a22-a47d-8c48425ef4a7',
   u'datasetName': u'iNaturalist research-grade observations',
   u'dateIdentified': u'2016-12-30T15:01:30',
   u'day': 23,
   u'decimalLatitude': 13.4756,
   u'decimalLongitude': 120.851388,
   u'eventDate': u'2016-12-23T04:00:00',
...

_

**Comment by sckott** [comment]
thanks for the report @aubreymoore having a look

**Comment by sckott** [comment]
looksl like your WKT has the wrong winding direction. 

GBIF docs have for the `geometry` parameter https://www.gbif.org/developer/occurrence#p_geometry

I'll update the docs on this. 

If you reverse the winding order of your WKT it works as expected I think:

```python3
geom_rev="POLYGON((144.61 13.22,144.96 13.22,144.96 13.66,144.61 13.66,144.61 13.22))"
res2 = occ.search(scientificName='Oryctes rhinoceros', geometry=geom_rev, limit=10)
[ z['country'] for z in res2['results'] ]

['Guam',
 'Guam',
 'Guam',
 'Guam',
 'Guam',
 'Guam',
 'Guam',
 'Guam',
 'Guam',
 'Guam']
```

```python3
[ [z['decimalLatitude'], z['decimalLongitude']] for z in res2['results'] ]

[[13.491572, 144.845642],
 [13.430427, 144.801009],
 [13.474637, 144.783201],
 [13.430502, 144.800539],
 [13.511599, 144.803081],
 [13.427608, 144.788581],
 [13.521747, 144.879896],
 [13.588958, 144.867862],
 [13.49438, 144.776794],
 [13.493889, 144.77417]]
```

I haven't found an easy Python lib for reversing winding order, but in R, you could 

```r
install.packages("wicket")
x = 'POLYGON((144.61 13.22, 144.61 13.66, 144.96 13.66, 144.96 13.22, 144.61 13.22))'
wicket::wkt_reverse(x)
```

**Comment by aubreymoore** [comment]
Thanks for the explanation. And thanks for maintaining this useful package.

**Comment by sckott** [comment]
the function is now in the library if you reinstall
