### ISSUE TITLE
Use type hints?

### ISSUE THREAD

**Issue by sckott** [sckott/pygbif#51]
see https://www.python.org/dev/peps/pep-0484/

@stijnvanhoey @peterdesmet any complaints if we use type hints?  i think it means python 3.5 or greater

**Comment by stijnvanhoey** [comment]
I don't think this should be an issue. Fine for me

**Comment by sckott** [comment]
thanks for the feedback @stijnvanhoey

**Comment by sckott** [comment]
not going to implement, can reopen if there's interest
