### ISSUE TITLE
Caching API requests

### ISSUE THREAD

**Issue by nleguillarme** [sckott/pygbif#52]
Python 3.7
pygbif 0.3.0

In my application, I send a lot of requests to get info from GBIF backbone taxonomy, sometimes with the same parameters. Ultimately, I plan to download the full taxonomic backbone, but in the meantime, I think it would be great to implement some caching mechanism, for instance using [requests-cache](https://pypi.org/project/requests-cache/).

Anyway, great work on this library. Thanks.

**Comment by sckott** [comment]
thanks for the issue @nleguillarme 

had a look at that pkg. is it more common for pkg maintainers to build in caching with a pkg like `requests-cache` or to point the user to doing it themselves?  I've never done this in Python so not sure what best practice is

**Comment by nleguillarme** [comment]
Hi @sckott.

That's a good question and I do not have enough experience to give you an answer.
As I am sending requests to a lot of different APIs in my app, I use two useful tools to make it more robust :

- Caching to improve performance and avoid hitting rate limits
- [Retry sessions](https://www.peterbe.com/plog/best-practice-with-retries-with-requests) to handle ConnectionError due to unreliable network or rate limits

I think both could be easily integrated in pygbif by the pkg user himself by allowing the use of a custom session (a CachedSession from requests-cache and/or a session with Retry).

**Comment by sckott** [comment]
thanks, and sorry for the delay, will try to get something built in soon ...

**Comment by sckott** [comment]
@nleguillarme reinstall from branch `caching` `[sudo] pip install git+git://github.com/sckott/pygbif.git@caching#egg=pygbif`

uses requests-cache library now, see method `pygbif.caching` - let me know what you think, see docs for it `??pygbif.caching` in ipython

**Comment by sckott** [comment]
also, curious if any comments from @peterdesmet @stijnvanhoey @damianooldoni on this ☝️

**Comment by nleguillarme** [comment]
Hi, thank you for your work.

I run into an issue when reinstalling pygbif from the caching branch with
`sudo pip install git+https://github.com/sckott/pygbif.git@caching#egg=pygbif`

`Collecting pygbif from git+https://github.com/sckott/pygbif.git@caching#egg=pygbif
  Cloning https://github.com/sckott/pygbif.git (to caching) to /tmp/pip-build-7o4QB8/pygbif
Requirement already satisfied: requests>2.7 in /home/leguilln/.local/lib/python2.7/site-packages (from pygbif)
Collecting requests-cache (from pygbif)
  Downloading https://files.pythonhosted.org/packages/7f/55/9b1c40eb83c16d8fc79c5f6c2ffade04208b080670fbfc35e0a5effb5a92/requests_cache-0.5.2-py2.py3-none-any.whl
Collecting geojson_rewind (from pygbif)
  Downloading https://files.pythonhosted.org/packages/ce/f2/7adbb1f4e0568749219108efde5180a88788ca59d8d71315a8449120f614/geojson-rewind-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7o4QB8/geojson-rewind/setup.py", line 18, in <module>
        long_description=_get_description(),
      File "/tmp/pip-build-7o4QB8/geojson-rewind/setup.py", line 7, in _get_description
        with open(path, encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7o4QB8/geojson-rewind/`

FYI, 
`pip -V
pip 19.3.1 from /home/leguilln/workspace/python3.7-env/lib/python3.7/site-packages/pip (python 3.7)`

**Comment by nleguillarme** [comment]
Hi @sckott. Thank you for your work. Everything seem to work fine. I tested some scripts that get info from GBIF and never reached the request limit. When re-running the scripts, all results are obtained from the cache, which dramatically speed up the process.

**Comment by sckott** [comment]
Great, glad it works. I'll submit a new version to pypi soon

**Comment by abubelinha** [comment]
> * [Retry sessions](https://www.peterbe.com/plog/best-practice-with-retries-with-requests) to handle ConnectionError due to unreliable network or rate limits

Your link helped to solve [one of those situations](https://github.com/gbif/gbif-api/issues/128). Thanks @nleguillarme 

I take the opportunity to ask: 
Apart from the caching system issued here, does pygbif include any builtin timeout/retry control system?
i.e., how can I tell to pygbif to wait up to max 30 seconds, and retry up to 15 times

Thanks
@abubelinha

**Comment by abubelinha** [comment]
> When re-running the scripts, all results are obtained from the cache, which dramatically speed up the process.

I think that happens only if previous script runs finished without error. 
If you run a long loop and it is killed by a timeout error or if you kill the script before the loop ends ... then nothing is written to cache. Am I right?
@nleguillarme @sckott  Do you have idea of how to [write to cache at any time](https://github.com/gbif/pygbif/issues/146), to avoid that problem to happen?

**Comment by sckott** [comment]
sorry, i can't help. I no longer work on this project - & anyway it's been too long and I dont remember this work - hopefully the current maintainers will pop in
