### ISSUE TITLE
Latin name gender matching

### ISSUE THREAD

**Issue by qgroom** [sckott/pygbif#55]
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
pygbif 0.3.0

When querying GBIF using `name_suggest` the name Lantanophaga pusillidactyl**a** is not found. Apparently, it has been written in the wrong gender form. However, the GBIF website given the same query returns the results for Lantanophaga pusillidactyl**us**.

Is it possible to include this functionality in pygbif?

**Comment by sckott** [comment]
Thanks for your question @qgroom 

The short answer is: I don't know for sure how to get the same behavior. 

pygbif does have `name_lookup` which uses the `/species/search` route here https://www.gbif.org/developer/species#searching - more of a full text search of names. That method gets closer, but still gives a lot of results of the **a** ending:

```python
from pygbif import species
z = species.name_lookup(q='Lantanophaga pusillidactyla', status = "ACCEPTED")
In [14]: [ w['scientificName'] for w in z['results'] ]
Out[14]:
['Lantanophaga pusillidactyla',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla Walker 1864',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactyla (Walker, 1864)',
 'Lantanophaga pusillidactylus (Walker, 1864)',
 'Lantanophaga pusillidactylus (Walker, 1864)',
 'Lantanophaga pusillidactylus (Walker, 1864)',
 'Lantanophaga pusillidactylus (Walker, 1864)',
 'Lantanophaga pussillidactyla (Walker, 1864)',
# cutoff ...] 
```

I had a look at the gbif site with browser dev tools, but i think it's a slightly different internal set of APIs they're using.

@timrobertson100 any thoughts on how to replicate what the gbif website does wrt name searching?

**Comment by MortenHofft** [comment]
The species match API might be what you are looking for?
http://api.gbif.org/v1/species/match?name=Lantanophaga%20pusillidactyla

Or for species search it might be good to include a datasetKey=backbone
https://api.gbif.org/v1/species/search?q=Lantanophaga%20pusillidactyla&datasetKey=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c

does that help?

**Comment by sckott** [comment]
thanks @MortenHofft - right, we have that route implemented in `name_backbone` method 

Perhaps `species.name_backbone('Lantanophaga pusillidactyla')` does what you want @qgroom

**Comment by qgroom** [comment]
Thanks, I'll give it a try and get back to you.

**Comment by qgroom** [comment]
Yes, that works. Perhaps a note is required in the documentation, but then I don't suppose anyone will read it.

**Comment by sckott** [comment]
glad it works. 

>  I don't suppose anyone will read it.

agree, but i guess its the right thing to do
