### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by nleguillarme** [sckott/pygbif#57]
Hi, I'm trying to download occurrence data and run into an exception. Here is my code:
`   from pygbif import occurrences as occ

    key = 2473421
    download_info = occ.download(
        user=my_user_name,
        pwd=my_pwd,
        email=my_email,
        queries=["taxonKey = {}".format(key)]
    )

    if len(download_info) > 0:
        occ.download_get(key=download_info[0])`

And the error :
`File "/home/leguilln/workspace/python3.7-env/lib/python3.7/site-packages/pygbif/occurrences/download.py", line 384, in download_get
    raise Exception('download "%s" not of status SUCCEEDED' % key)
Exception: download "0014929-191105090559680" not of status SUCCEEDED`

Thank you for your help.

**Comment by sckott** [comment]
thanks for your question @nleguillarme 

if you pass the key to `download_meta` you can get the status: `occ.download_meta(key=download_info[0])`

The GBIF download service is not like the search service (e.g., `occ.search`). The search service returns data right away, whereas the download service kicks off a background job, and only after it finishes running can you then request the data. 

You can add another line of code to check the status of the job and then only run `download_get` when the job is of status `SUCCEEDED`

**Comment by nleguillarme** [comment]
Thank you @sckott for these explanations.

**Comment by sckott** [comment]
Do you need any further help on this?

**Comment by nleguillarme** [comment]
So I have a loop to regularly check if the status of the job has changed, but even after receiving the mail from GBIF saying my data download is ready, the status is still "RUNNING", so I have no idea when I can start downloading the archive.

**Comment by sckott** [comment]
thanks, i'll have a look - what is the download ID?

**Comment by sckott** [comment]
I didn't have an issue creating a download then checking with `download_meta` - maybe it's a problem with that one download -
