### ISSUE TITLE
I can't export coordinates of maps.map object 

### ISSUE THREAD

**Issue by juanpac96** [sckott/pygbif#58]
I have the Next code for exctract the coordinate from map
```
from pygbif import maps
x = maps.map(familiaKey = 4690, year = 2000, bin = "hex", country='CO',srs='EPSG:4326',
             hexPerTile = 500, style = "classic-noborder.poly",format = ".mvt")
x.response
x.path
x.img # None
import mapbox_vector_tile
result = mapbox_vector_tile.decode(x.response.content)
```
Next, I visualizate the data
```
result['occurrence']['features'][0]
# Output
{'geometry': {'coordinates': [[[2425, 2312],
    [2423, 2307],
    [2417, 2307],
    [2415, 2312],
    [2417, 2316],
    [2423, 2316],
    [2425, 2312]]],
  'type': 'Polygon'},
 'id': 0,
 'properties': {'total': 150},
 'type': 3}
```
My problem is in item for coordinate. Because I need in this format:
{'geometry': {'coordinates': [[[-75.3, 4.35],
    [-73.2423, 4.2307],
    [-75.2417, 5.2307],
    [-75.2415, 5.2312],
.........
How can i make the trasfomation? I need the coordinate in this way because I will create a GeoDataFrame with Geopandas.

This is the link of my notebook in Google Colab.
https://colab.research.google.com/drive/1noZlE6fFq39Qnhml2mTJk5BI2ksYRITA

**Comment by sckott** [comment]
Thanks for your question. I don't know how to convert the data to lat/long values. We do this in the R package rgbif, through the protolite pkg here https://github.com/jeroen/protolite/blob/master/R/mvt.R - i'll ask some folks if they know how to do this in python

**Comment by stijnvanhoey** [comment]
I do think https://github.com/mapbox/mercantile or https://github.com/tilezen/mapbox-vector-tile#decoding could be useful, but haven't tried this myself.

**Comment by sckott** [comment]
thanks @stijnvanhoey 

he is already using `mapbox_vector_tile.decode` above - but it returns tile coordinates, what he wants is the lat/long coords. 

mercantile might be useful here

**Comment by juanpac96** [comment]
I use one option to fix it, then is to apply the function 
`plt.hexbin(x,y,cmap=color_map,edgecolors='k',extent=(-81.735793,-66.870391,-4.250167,13.394803),
                       gridsize=bins,mincnt=1)`, 
where x and y are longitude and latitude, make this plot:
![image](https://user-images.githubusercontent.com/40966420/70957272-900ead00-2043-11ea-8e93-572d7904aaa6.png)

If you wanna see how I make this, I give you a notebook link for you:
https://colab.research.google.com/drive/16FPv6Ko3qFUqAyAaXO-aBHHJ57aDjy72

However, i see than my request is incomplete, because when I use: `occurrences.count(taxonKey=7707728, country='CO')` 

This return value of 2105267 registers, but when I call a quest like this:

`occurrences.search(phylumKey= 7707728, country='CO', limit=2e6)`

only get 300 datapoints..... anyone knows how can I get all the occurrences for my query?

**Comment by sckott** [comment]
the answer for the pagination is that GBIF allows 300 records per request. in `rgbif` we handle that pagination internally for the user, but here we don't. python tends to be a more technical set of users, so didn't do pagination for the user here. there's probably a better way to do it, but here's one way:

```python
from pygbif import occurrences
def gbif_search():
    limit = 300
    offset = 0
    endOfRecords = False
    out = []
    while not endOfRecords:
        x = occurrences.search(taxonKey = 9206251, country='MX',
            limit=limit, offset=offset)
        endOfRecords = x['endOfRecords']
        offset = sum([len(z['results']) for z in out]) + len(x["results"])
        out.append(x)
    return out

x = gbif_search()
sum([len(z['results']) for z in x])
```

**Comment by sckott** [comment]
I'll have a look at the notebook

**Comment by juanpac96** [comment]
I used your code and only change this part for my propose:
`x = occurrences.search(taxonKey=7707728, country='CO',
            limit=limit, offset=offset)` 

But I get the next error:
`HTTPError: 400 Client Error: Bad Request for url: https://api.gbif.org/v1/occurrence/search?taxonKey=7707728&country=CO&limit=300&offset=199800`

This error is the same when I try to get all occurrences with a for loop.

**Comment by sckott** [comment]
Sorry, didn't tell you the other information, that 200,000 is the max for offset+limit, see  https://www.gbif.org/developer/occurrence  - You can separate your requests into smaller bins with `.search`, or you can switch to the `.download` method - it's different syntax from .search, but is more flexible, and has the advantage that there's no limit on records

**Comment by sckott** [comment]
@juanpac96 so it looks like you figured out the mapping issue - given your comment in https://github.com/sckott/pygbif/issues/58#issuecomment-566341827 ?

**Comment by juanpac96** [comment]
Yes, I finally I did it. with download requests, I get it and found the solution to my issue.
![image](https://user-images.githubusercontent.com/40966420/71329628-68ad5980-24f5-11ea-93e2-ce8be9f60df3.png)

**Comment by sckott** [comment]
Great, nice work
