### ISSUE TITLE
Center map 

### ISSUE THREAD

**Issue by diallobakary4** [sckott/pygbif#61]
Hello 
How can center this map on the country ZA (South Africa). This should be quite trivial but I have been unsuccessfully playing with the coordinates (see bellow). Or should simply resize the generated figure?

![map_resize](https://user-images.githubusercontent.com/13533717/78228600-35547080-74cf-11ea-817c-b698cb5f57b2.gif)

Thanks

**Comment by sckott** [comment]
thanks for your question @diallobakary4 - i'll have a look and get back to you soon

**Comment by sckott** [comment]
sorry, I tried but can't figure out how to center. there is an `extent` parameter on `matplotlib.pyplot.imshow` (which we use internally), which seems promising, but I don't know how to use it exactly

**Comment by diallobakary4** [comment]
OK thank you.
Will look into that.
