### ISSUE TITLE
Online documentation not up-to-date?

### ISSUE THREAD

**Issue by niconoe** [sckott/pygbif#66]
The documentation online (https://pygbif.readthedocs.io/en/latest/) refers to v0.3 as "latest", while version 0.4 is available both on PyPI and as a GitHub release.

If this documentation upload process is not fully automated, a possible improvement would be to describe it in the "contributing" doc. For my personal projects, I generally try to document that, and also to write a "release checklist" to avoid forgetting such steps (see https://pyinaturalist.readthedocs.io/en/latest/infrastructure.html for example).

Tell me if I can help!

**Comment by sckott** [comment]
It is automated with readthedocs. For some reason build failures started happening and I never got around to sorting it out. 

Looks like for v0.4, https://github.com/sckott/pygbif/blob/v0.4.0/requirements.txt was missing `requests-cache` - I got the latest version on master to build by adding that pkg to `requirements.txt`, but I'm not sure how to get the v0.4 tag to build if the `requirements.txt` is missing a package. DO you know know a way?  

Docs are pointing to master now - see https://pygbif.readthedocs.io/en/latest/index.html 

We should add something about docs and readthedocs to Contributing file

**Comment by niconoe** [comment]
I can now see v0.4 in the title on https://pygbif.readthedocs.io/en/latest/index.html, so I guess your changes fixed it, thanks!
