### ISSUE TITLE
Obtain format of StillImage 

### ISSUE THREAD

**Issue by faroit** [sckott/pygbif#74]
Hi, I am about to write a tool to automatically fetch media from GBIF occurances on top of pybif. 

I wonder what is the best way to obtain the format of the media attachments since some of the data providers did not submit the format type...

e.g. compare

https://api.gbif.org/v1/occurrence/2575119654  (`"format": "image/jpeg"` is present)

with

https://api.gbif.org/v1/occurrence/2644190689  (`format` is not present)

now, adding the gbif API extensions using https://api.gbif.org/v1/occurrence/2644190689/verbatim would make it possible to obtain the format. However, I am not sure if this is only determined by the file extension or if this is analyzed and added on GBIF. If the latter is the case, I would propose to add this to pybif. If not, feel free to close this as this has to be discussed on the api side of GBIF then.

**Comment by sckott** [comment]
Thanks for the issue @faroit 

@timrobertson100 @MattBlissett Do either of you know how the media format is determined? See above

**Comment by faroit** [comment]
any update on this? should I bring this up somewhere at GBIF?

**Comment by timrobertson100** [comment]
Sorry, this went unanswered for so long.

The first record comes to us with a format of `image/jpeg` while the second has `jpeg`. The [parser](https://github.com/gbif/pipelines/blob/dbdc6f084170183918fd4cd2832942a1fa847d1f/sdks/core/src/main/java/org/gbif/pipelines/core/interpreters/extension/MultimediaInterpreter.java#L168) is using a [Mime type parser](https://github.com/gbif/parsers/blob/7e8c9aeebfcd1b680e7d4852b02e75d01a5c0334/src/main/java/org/gbif/common/parsers/MediaParser.java#L95) which underneath uses Apache Tika. Tracing that through, it seems Tika is pretty strict and expects a well-formed MIME type as described in the [supported formats](https://tika.apache.org/1.19.1/formats.html#Full_list_of_Supported_Formats).

This seems poor, given the code would also detect it from a URL ending in "...jpg" anyway. I've opened [this issue](https://github.com/gbif/pipelines/issues/420) to fix it.

**Comment by faroit** [comment]
@timrobertson100 sounds great, thanks a a lot. I guess it makes sense to close this issue here, since its out of scope of pygbif then.

**Comment by sckott** [comment]
thanks @timrobertson100

**Comment by AntoineAA** [comment]
Hi,

The example given by Faro (https://api.gbif.org/v1/occurrence/2644190689) corresponds to an observation from our first data publication through the IPT server.

I made a mistake with the "format" field by specifying "jpeg".

My next dump will include the well-formed MIME type format (Tika compliant) "image/jpeg".

I should be able to publish a new version of our two datasets before the end of the year.
