### ISSUE TITLE
Allow to set verbosity level of get_download

### ISSUE THREAD

**Issue by faroit** [sckott/pygbif#78]
`download_get` produces print statements that users might want to hide if they:

e.g.

`
Download file size: 984374 bytes
On disk at /var/folders/4p/m3ccc38s0fg5b3c0zb1mdpph0000gn/T/tmpkzsf605i/0117522-200613084148143.zip
`

Maybe a `verbose=False` flag would be suffucient here? Ideally, there would be consistent usage of `logging` to set this package-wide.

Let me know what you think

**Comment by sckott** [comment]
Sure, sounds good to set it package wide. Any best practice for doing that?

**Comment by faroit** [comment]
there are many packages to handle this nicely, but common practice seems still using `logging` and set some global config for it https://docs.python.org/3/library/logging.config.html

**Comment by sckott** [comment]
thanks, some other notes

- https://stackoverflow.com/a/15729700/1091766
- https://docs.python.org/3/howto/logging-cookbook.html

**Comment by sckott** [comment]
@faroit can you reinstall and try again?

**Comment by faroit** [comment]
@sckott thanks a lot. I tried them and it works as advertised :+1:
